all:
  hosts:
    trckr001:
      ansible_host: 192.168.xxx.xxx
    trckr002:
      ansible_host: 192.168.xxx.xxx
    trckr003:
      ansible_host: 192.168.xxx.xxx
    trckr004:
      ansible_host: 192.168.xxx.xxx
    trckr005:
      ansible_host: 192.168.xxx.xxx
    trckr006:
      ansible_host: 192.168.xxx.xxx
    trckr007:
      ansible_host: 192.168.xxx.xxx
    trckr008:
      ansible_host: 192.168.xxx.xxx
    trckr009:
      ansible_host: 192.168.xxx.xxx
    trckr010:
      ansible_host: 192.168.xxx.xxx
    trckr011:
      ansible_host: 192.168.xxx.xxx
    trckr012:
      ansible_host: 192.168.xxx.xxx
    trckr013:
      ansible_host: 192.168.xxx.xxx
    trckr014:
      ansible_host: 192.168.xxx.xxx
    trckr015:
      ansible_host: 192.168.xxx.xxx
    trckr016:
      ansible_host: 192.168.xxx.xxx
    trckr017:
      ansible_host: 192.168.xxx.xxx
    trckr018:
      ansible_host: 192.168.xxx.xxx
    trckr019:
      ansible_host: 192.168.xxx.xxx
    trckr020:
      ansible_host: 192.168.xxx.xxx
    trckr021:
      ansible_host: 192.168.xxx.xxx
    trckr022:
      ansible_host: 192.168.xxx.xxx
    trckr023:
      ansible_host: 192.168.xxx.xxx
    trckr024:
      ansible_host: 192.168.xxx.xxx
    trckr025:
      ansible_host: 192.168.xxx.xxx
    trckr026:
      ansible_host: 192.168.xxx.xxx
    trckr028:
      ansible_host: 192.168.xxx.xxx
    trckr029:
      ansible_host: 192.168.xxx.xxx
    trckr030:
      ansible_host: 192.168.xxx.xxx
    trckr031:
      ansible_host: 192.168.xxx.xxx
    trckr032:
      ansible_host: 192.168.xxx.xxx
    trckr033:
      ansible_host: 192.168.xxx.xxx
    trckr034:
      ansible_host: 192.168.xxx.xxx
    trckr035:
      ansible_host: 192.168.xxx.xxx
    trckr037:
      ansible_host: 192.168.xxx.xxx
    trckr039:
      ansible_host: 192.168.xxx.xxx
    trckr040:
      ansible_host: 192.168.xxx.xxx
    trckr041:
      ansible_host: 192.168.xxx.xxx
    trckr042:
      ansible_host: 192.168.xxx.xxx
    trckr043:
      ansible_host: 192.168.xxx.xxx

  children:
    ST_Internal:
      hosts:
        trckr001:
        trckr002:

    ST_Space:
      hosts:
        trckr003:
        trckr004:
        trckr005:
        trckr006:
        trckr007:
        trckr008:
        trckr009:
        trckr010:
        trckr011:
        trckr012:

    ST_passport_dashboard:
      hosts:
        trckr013:
        trckr014:

    ST_3Dsearch:
      hosts:
        trckr015:
        trckr016:

    ST_Builder:
      hosts:
        trckr017:
        trckr018:

    ST_Search:
      hosts:
        trckr019:
        trckr020:
        trckr021:
        trckr022:

    ST_crawler:
      hosts:
        trckr023:

    ST_3DComment:
      hosts:
        trckr024:
        trckr025:

    ST_3DNotification:
      hosts:
        trckr026:

    ST_3DSwym:
      hosts:
        trckr028:
        trckr029:

    ST_3DIndex:
      hosts:
        trckr030:

    ST_3DSwymIndex:
      hosts:
        trckr031:

    ST_FCS:
      hosts:
        trckr032:
        trckr033:
        trckr034:
        trckr035:

    ST_THEAI:
      hosts:
        trckr037:

    ST_DB_server:
      hosts:
        trckr039:

    ST_RFCS:
      hosts:
        trckr040:

    ST_Front_End:
      hosts:
        trckr041:
        trckr042:

    ST_Back_End:
      hosts:
        trckr043: