all:
  hosts:
    trckr001:
      ansible_host: 192.168.xxx.xxx
    trckr002:
      ansible_host: 192.168.xxx.xxx
   
UnmountDIR:
  hosts:
    trckr001:
    trckr002:
    trckr003:
    trckr004:
   
CheckmountDIR:
  hosts:
    trckr001:
    trckr002:

TerraceUnmountDIR:
  hosts:
    trckr001:
    trckr002:

TerraceCheckmountDIR:
  hosts:
    trckr001:
    trckr002: