all:
  children:
    Space:
      hosts:
        trckr001:
          ansible_host: 192.168.1.10
        trckr002:
          ansible_host: 192.168.1.11

    passport:
      hosts:
        trckr003:
          ansible_host: 192.168.1.12
        trckr004:
          ansible_host: 192.168.1.13

    TerraceCheckmountDIR:
      hosts:
        trckr001:
        trckr002:

    TerraceUnmountDIR:
      hosts:
        trckr001:
        trckr002:
