all:
  hosts:
    trcsr001:
      ansible_host: 192.168.xxx.xxx
    trcsr002:
      ansible_host: 192.168.xxx.xxx
    trcsr003:
      ansible_host: 192.168.xxx.xxx
    trcsr004:
      ansible_host: 192.168.xxx.xxx
    trcsr005:
      ansible_host: 192.168.xxx.xxx
    trcsr006:
      ansible_host: 192.168.xxx.xxx
    trcsr007:
      ansible_host: 192.168.xxx.xxx
    trcsr008:
      ansible_host: 192.168.xxx.xxx
    trcsr009:
      ansible_host: 192.168.xxx.xxx
    trcsr010:
      ansible_host: 192.168.xxx.xxx
    trcsr011:
      ansible_host: 192.168.xxx.xxx
    trcsr012:
      ansible_host: 192.168.xxx.xxx
    trcsr013:
      ansible_host: 192.168.xxx.xxx
    trcsr014:
      ansible_host: 192.168.xxx.xxx
    trcsr015:
      ansible_host: 192.168.xxx.xxx
    trcsr016:
      ansible_host: 192.168.xxx.xxx
    trcsr017:
      ansible_host: 192.168.xxx.xxx
    trcsr018:
      ansible_host: 192.168.xxx.xxx
    trcsr019:
      ansible_host: 192.168.xxx.xxx
    trcsr020:
      ansible_host: 192.168.xxx.xxx
    trcsr021:
      ansible_host: 192.168.xxx.xxx
    trcsr022:
      ansible_host: 192.168.xxx.xxx
    trcsr023:
      ansible_host: 192.168.xxx.xxx
    trcsr024:
      ansible_host: 192.168.xxx.xxx
    trcsr025:
      ansible_host: 192.168.xxx.xxx
    trcsr026:
      ansible_host: 192.168.xxx.xxx
    trcsr027:
      ansible_host: 192.168.xxx.xxx
    trcsr028:
      ansible_host: 192.168.xxx.xxx
    trcsr029:
      ansible_host: 192.168.xxx.xxx
    trcsr030:
      ansible_host: 192.168.xxx.xxx
    trcsr031:
      ansible_host: 192.168.xxx.xxx
    trcsr034:
      ansible_host: 192.168.xxx.xxx
    trcsr039:
      ansible_host: 192.168.xxx.xxx
    trcsr040:
      ansible_host: 192.168.xxx.xxx
    trcsr041:
      ansible_host: 192.168.xxx.xxx
    trcsr042:
      ansible_host: 192.168.xxx.xxx
    trcsr043:
      ansible_host: 192.168.xxx.xxx
    trcsr044:
      ansible_host: 192.168.xxx.xxx
    trcsr045:
      ansible_host: 192.168.xxx.xxx
    trcsr046:
      ansible_host: 192.168.xxx.xxx

  children:
    DH_Front_End:
      hosts:
        trcsr001:
        trcsr002:

    DH_Back_End:
      hosts:
        trcsr003:

    DH_Customize_DB:
      hosts:
        trcsr004:

    WBDM:
      hosts:
        trcsr005:
        trcsr006:

    Internal:
      hosts:
        trcsr007:
        trcsr008:

    Space:
      hosts:
        trcsr009:
        trcsr010:

    passport_dashboard:
      hosts:
        trcsr011:
        trcsr012:

    3Dsearch:
      hosts:
        trcsr013:
        trcsr014:

    Builder:
      hosts:
        trcsr015:
        trcsr016:

    Search:
      hosts:
        trcsr017:
        trcsr018:
        trcsr019:
        trcsr020:

    crawler:
      hosts:
        trcsr021:

    3DComment:
      hosts:
        trcsr022:
        trcsr023:

    3DNotification:
      hosts:
        trcsr024:
        trcsr025:

    3DSwym:
      hosts:
        trcsr026:
        trcsr027:

    3DIndex:
      hosts:
        trcsr028:

    3DSwymIndex:
      hosts:
        trcsr029:

    FCS:
      hosts:
        trcsr030:
        trcsr031:

    Onepart:
      hosts:
        trcsr034:

    Backup_MRTG:
      hosts:
        trcsr039:

    BEV_Front_End:
      hosts:
        trcsr040:
        trcsr041:

    BEV_Back_End:
      hosts:
        trcsr042:

    C4_Front_End:
      hosts:
        trcsr043:
        trcsr044:

    C4_Back_End:
      hosts:
        trcsr045:

    THEAI:
      hosts:
        trcsr046: