all:
  hosts:
    trcsr001:
      ansible_host: 192.168.xxx.xxx
    trcsr002:
      ansible_host: 192.168.xxx.xxx

  children:
    UnmountDIR:
      hosts:
        trcsr001:
        trcsr002:

    CheckmountDIR:
      hosts:
        trcsr001:
        trcsr002:

    TerraceCheckmountDIR:
      hosts:
        trcsr001:
        trcsr002:

    TerraceUnmountDIR:
      hosts:
        trcsr001:
        trcsr002:
