---
- hosts: all
  become: true

  vars_files:
    - "../../inventory/RE/group_vars/all.yml"

  tasks:
    - name: Check Mount C4_Back_End
      ansible.builtin.shell:
        cmd: "mount | grep -i '{{ item }}'"
      become_user: "{{ oracle_user }}" # เรียกใช้ตรงนี้ ตัวแปรจะอ่านค่าได้พอดี
      register: result
      failed_when: result.rc != 0
      loop:
        - /
        - /proc
      when: "'C4_Back_End' in group_names"