all:
  hosts:
    trckr001:
      ansible_host: 192.168.xxx.xxx
    trckr003:
      ansible_host: 192.168.xxx.xxx
    trckr004:
      ansible_host: 192.168.xxx.xxx
    trckr005:
      ansible_host: 192.168.xxx.xxx
    trckr006:
      ansible_host: 192.168.xxx.xxx
    trckr007:
      ansible_host: 192.168.xxx.xxx
    trckr013:
      ansible_host: 192.168.xxx.xxx
    trckr015:
      ansible_host: 192.168.xxx.xxx
    trckr017:
      ansible_host: 192.168.xxx.xxx
    trckr019:
      ansible_host: 192.168.xxx.xxx
    trckr020:
      ansible_host: 192.168.xxx.xxx
    trckr023:
      ansible_host: 192.168.xxx.xxx
    trckr024:
      ansible_host: 192.168.xxx.xxx
    trckr026:
      ansible_host: 192.168.xxx.xxx
    trckr028:
      ansible_host: 192.168.xxx.xxx
    trckr030:
      ansible_host: 192.168.xxx.xxx
    trckr032:
      ansible_host: 192.168.xxx.xxx
    trckr033:
      ansible_host: 192.168.xxx.xxx
    trckr037:
      ansible_host: 192.168.xxx.xxx
    trckr039:
      ansible_host: 192.168.xxx.xxx
    trckr041:
      ansible_host: 192.168.xxx.xxx
    trckr043:
      ansible_host: 192.168.xxx.xxx

  children:
    ST_Phase1:
      children:
        ST1_Internal:
          hosts:
            trckr001:

        ST1_Space:
          hosts:
            trckr003:
            trckr004:
            trckr005:
            trckr006:
            trckr007:

        ST1_passport_dashboard:
          hosts:
            trckr013:

        ST1_3Dsearch:
          hosts:
            trckr015:

        ST1_Builder:
          hosts:
            trckr017:

        ST1_Search:
          hosts:
            trckr019:
            trckr020:

        ST1_crawler:
          hosts:
            trckr023:

        ST1_3DComment:
          hosts:
            trckr024:

        ST1_3DNotification:
          hosts:
            trckr026:

        ST1_3DSwym:
          hosts:
            trckr028:

        ST1_3DIndex:
          hosts:
            trckr030:

        ST1_FCS:
          hosts:
            trckr032:
            trckr033:

        ST1_THEAI:
          hosts:
            trckr037:

        ST1_DB_server:
          hosts:
            trckr039:

        ST1_Front_End:
          hosts:
            trckr041:

        ST1_Back_End:
          hosts:
            trckr043: