all:
  hosts:
    trckr001:
      ansible_host: 192.168.120.56
    trckr003:
      ansible_host: 192.168.120.56
    trckr004:
      ansible_host: 192.168.120.56
    trckr005:
      ansible_host: 192.168.120.56
    trckr006:
      ansible_host: 192.168.120.56
    trckr007:
      ansible_host: 192.168.120.56
    trckr013:
      ansible_host: 192.168.120.56
    trckr015:
      ansible_host: 192.168.120.56
    trckr017:
      ansible_host: 192.168.120.56
    trckr019:
      ansible_host: 192.168.120.56
    trckr020:
      ansible_host: 192.168.120.56
    trckr023:
      ansible_host: 192.168.120.56
    trckr024:
      ansible_host: 192.168.120.56
    trckr026:
      ansible_host: 192.168.120.56
    trckr028:
      ansible_host: 192.168.120.56
    trckr030:
      ansible_host: 192.168.120.56
    trckr032:
      ansible_host: 192.168.120.56
    trckr033:
      ansible_host: 192.168.120.56
    trckr037:
      ansible_host: 192.168.120.56
    trckr039:
      ansible_host: 192.168.120.56
    trckr041:
      ansible_host: 192.168.120.56
    trckr043:
      ansible_host: 192.168.120.56

  children:
    ST_Phase1:
      children:
        Internal:
          hosts:
            trckr001:

        Space:
          hosts:
            trckr003:
            trckr004:
            trckr005:
            trckr006:
            trckr007:

        passport_dashboard:
          hosts:
            trckr013:

        3Dsearch:
          hosts:
            trckr015:

        Builder:
          hosts:
            trckr017:

        Search:
          hosts:
            trckr019:
            trckr020:

        crawler:
          hosts:
            trckr023:

        3DComment:
          hosts:
            trckr024:

        3DNotification:
          hosts:
            trckr026:

        3DSwym:
          hosts:
            trckr028:

        3DIndex:
          hosts:
            trckr030:

        FCS:
          hosts:
            trckr032:
            trckr033:

        THEAI:
          hosts:
            trckr037:

        DB_server:
          hosts:
            trckr039:

        Front_End:
          hosts:
            trckr041:

        Back_End:
          hosts:
            trckr043: