---
- hosts: all
  become: true

  tasks:
    - name: Mount Check 
      ansible.builtin.shell:
        cmd: "mount | grep -i '{{ item }}'"
      register: result
      failed_when: result.rc != 0
      loop:
        - /usr1/NAS
        - /3dex_data
      when: "'CheckmountDIR' in group_names"