---
- hosts: all
  become: true
  tasks:
    - name: Check Mount ST_Internal
      ansible.builtin.shell:
        cmd: "mount | grep -i '{{ item }}'"
      register: result
      failed_when: result.rc != 0
      loop:
        - /appshare01
        - /appshare02
        - /usr1/NAS
      when: "'ST_Internal' in group_names"

    - name: Check Mount ST_Space
      ansible.builtin.shell:
        cmd: "mount | grep -i '{{ item }}'"
      register: result
      failed_when: result.rc != 0
      loop:
        - /appshare01
        - /appshare02
        - /usr1/NAS
      when: "'ST_Space' in group_names"

    - name: Check Mount ST_passport_dashboard
      ansible.builtin.shell:
        cmd: "mount | grep -i '{{ item }}'"
      register: result
      failed_when: result.rc != 0
      loop:
        - /usr1/NAS
      when: "'ST_passport_dashboard' in group_names"

    - name: Check Mount ST_3Dsearch
      ansible.builtin.shell:
        cmd: "mount | grep -i '{{ item }}'"
      register: result
      failed_when: result.rc != 0
      loop:
        - /usr1/NAS
      when: "'ST_3Dsearch' in group_names"

    - name: Check Mount ST_Builder
      ansible.builtin.shell:
        cmd: "mount | grep -i '{{ item }}'"
      register: result
      failed_when: result.rc != 0
      loop:
        - /usr1/NAS
        - /3dex_data_NAS
      when: "'ST_Builder' in group_names"

    - name: Check Mount ST_Search
      ansible.builtin.shell:
        cmd: "mount | grep -i '{{ item }}'"
      register: result
      failed_when: result.rc != 0
      loop:
        - /usr1/NAS
        - /3dex_data_NAS
      when: "'ST_Search' in group_names"

    - name: Check Mount ST_crawler
      ansible.builtin.shell:
        cmd: "mount | grep -i '{{ item }}'"
      register: result
      failed_when: result.rc != 0
      loop:
        - /usr1/NAS
      when: "'ST_crawler' in group_names"

    - name: Check Mount ST_3DComment
      ansible.builtin.shell:
        cmd: "mount | grep -i '{{ item }}'"
      register: result
      failed_when: result.rc != 0
      loop:
        - /usr1/NAS
        - /3dex_data
      when: "'ST_3DComment' in group_names"

    - name: Check Mount ST_3DNotification
      ansible.builtin.shell:
        cmd: "mount | grep -i '{{ item }}'"
      register: result
      failed_when: result.rc != 0
      loop:
        - /usr1/NAS
      when: "'ST_3DNotification' in group_names"

    - name: Check Mount ST_3DSwym
      ansible.builtin.shell:
        cmd: "mount | grep -i '{{ item }}'"
      register: result
      failed_when: result.rc != 0
      loop:
        - /usr1/NAS
        - /3dswym_data
      when: "'ST_3DSwym' in group_names"

    - name: Check Mount ST_3DIndex
      ansible.builtin.shell:
        cmd: "mount | grep -i '{{ item }}'"
      register: result
      failed_when: result.rc != 0
      loop:
        - /usr1/NAS
      when: "'ST_3DIndex' in group_names"

    - name: Check Mount ST_3DSwymIndex
      ansible.builtin.shell:
        cmd: "mount | grep -i '{{ item }}'"
      register: result
      failed_when: result.rc != 0
      loop:
        - /usr1/NAS
        - /3dswym_data
      when: "'ST_3DSwymIndex' in group_names"

    - name: Check Mount ST_FCS
      ansible.builtin.shell:
        cmd: "mount | grep -i '{{ item }}'"
      register: result
      failed_when: result.rc != 0
      loop:
        - /usr1/NAS
        - /3dex_data
      when: "'ST_FCS' in group_names"

    - name: Check Mount ST_Front_End
      ansible.builtin.shell:
        cmd: "mount | grep -i '{{ item }}'"
      register: result
      failed_when: result.rc != 0
      loop:
        - /usr1/NAS
        - /3dex_data
      when: "'ST_Front_End' in group_names"

    - name: Check Mount ST_Back_End
      ansible.builtin.shell:
        cmd: "mount | grep -i '{{ item }}'"
      register: result
      failed_when: result.rc != 0
      loop:
        - /usr1/NAS
      when: "'ST_Back_End' in group_names"