---
- hosts: all
  become: true
  tasks:
    - name: Unmount ST_Internal
      ansible.builtin.mount:
        path: "{{ item }}"
        state: unmounted
      loop:
        - /appshare01
        - /appshare02
        - /usr1/NAS
      when: "'ST_Internal' in group_names"

    - name: Unmount ST_Space
      ansible.builtin.mount:
        path: "{{ item }}"
        state: unmounted
      loop:
        - /appshare01
        - /appshare02
        - /usr1/NAS
      when: "'ST_Space' in group_names"

    - name: Unmount ST_passport_dashboard
      ansible.builtin.mount:
        path: "{{ item }}"
        state: unmounted
      loop:
        - /usr1/NAS
      when: "'ST_passport_dashboard' in group_names"

    - name: Unmount ST_3Dsearch
      ansible.builtin.mount:
        path: "{{ item }}"
        state: unmounted
      loop:
        - /usr1/NAS
      when: "'ST_3Dsearch' in group_names"

    - name: Unmount ST_Builder
      ansible.builtin.mount:
        path: "{{ item }}"
        state: unmounted
      loop:
        - /usr1/NAS
        - /3dex_data_NAS
      when: "'ST_Builder' in group_names"

    - name: Unmount ST_Search
      ansible.builtin.mount:
        path: "{{ item }}"
        state: unmounted
      loop:
        - /usr1/NAS
        - /3dex_data_NAS
      when: "'ST_Search' in group_names"

    - name: Unmount ST_crawler
      ansible.builtin.mount:
        path: "{{ item }}"
        state: unmounted
      loop:
        - /usr1/NAS
      when: "'ST_crawler' in group_names"

    - name: Unmount ST_3DComment
      ansible.builtin.mount:
        path: "{{ item }}"
        state: unmounted
      loop:
        - /usr1/NAS
        - /3dex_data
      when: "'ST_3DComment' in group_names"

    - name: Unmount ST_3DNotification
      ansible.builtin.mount:
        path: "{{ item }}"
        state: unmounted
      loop:
        - /usr1/NAS
      when: "'ST_3DNotification' in group_names"

    - name: Unmount ST_3DSwym
      ansible.builtin.mount:
        path: "{{ item }}"
        state: unmounted
      loop:
        - /usr1/NAS
        - /3dswym_data
      when: "'ST_3DSwym' in group_names"

    - name: Unmount ST_3DIndex
      ansible.builtin.mount:
        path: "{{ item }}"
        state: unmounted
      loop:
        - /usr1/NAS
      when: "'ST_3DIndex' in group_names"

    - name: Unmount ST_3DSwymIndex
      ansible.builtin.mount:
        path: "{{ item }}"
        state: unmounted
      loop:
        - /usr1/NAS
        - /3dswym_data
      when: "'ST_3DSwymIndex' in group_names"

    - name: Unmount ST_FCS
      ansible.builtin.mount:
        path: "{{ item }}"
        state: unmounted
      loop:
        - /usr1/NAS
        - /3dex_data
      when: "'ST_FCS' in group_names"

    - name: Unmount ST_Front_End
      ansible.builtin.mount:
        path: "{{ item }}"
        state: unmounted
      loop:
        - /usr1/NAS
        - /3dex_data
      when: "'ST_Front_End' in group_names"

    - name: Unmount ST_Back_End
      ansible.builtin.mount:
        path: "{{ item }}"
        state: unmounted
      loop:
        - /usr1/NAS
      when: "'ST_Back_End' in group_names"