---
- hosts: all
  become: true
  tasks:
    - name: Unmount Internal
      ansible.builtin.mount:
        path: "{{ item }}"
        state: unmounted
      loop:
        - /appshare01
        - /appshare02
        - /usr1/NAS
      when: "'Internal' in group_names"

    - name: Unmount Space
      ansible.builtin.mount:
        path: "{{ item }}"
        state: unmounted
      loop:
        - /appshare01
        - /appshare02
        - /usr1/NAS
      when: "'Space' in group_names"

    - name: Unmount passport_dashboard
      ansible.builtin.mount:
        path: "{{ item }}"
        state: unmounted
      loop:
        - /usr1/NAS
      when: "'passport_dashboard' in group_names"

    - name: Unmount 3Dsearch
      ansible.builtin.mount:
        path: "{{ item }}"
        state: unmounted
      loop:
        - /usr1/NAS
      when: "'3Dsearch' in group_names"

    - name: Unmount Builder
      ansible.builtin.mount:
        path: "{{ item }}"
        state: unmounted
      loop:
        - /usr1/NAS
        - /3dex_data_NAS
      when: "'Builder' in group_names"

    - name: Unmount Search
      ansible.builtin.mount:
        path: "{{ item }}"
        state: unmounted
      loop:
        - /usr1/NAS
        - /3dex_data_NAS
      when: "'Search' in group_names"

    - name: Unmount crawler
      ansible.builtin.mount:
        path: "{{ item }}"
        state: unmounted
      loop:
        - /usr1/NAS
      when: "'crawler' in group_names"

    - name: Unmount 3DComment
      ansible.builtin.mount:
        path: "{{ item }}"
        state: unmounted
      loop:
        - /usr1/NAS
        - /3dex_data
      when: "'3DComment' in group_names"

    - name: Unmount 3DNotification
      ansible.builtin.mount:
        path: "{{ item }}"
        state: unmounted
      loop:
        - /usr1/NAS
      when: "'3DNotification' in group_names"

    - name: Unmount 3DSwym
      ansible.builtin.mount:
        path: "{{ item }}"
        state: unmounted
      loop:
        - /usr1/NAS
        - /3dswym_data
      when: "'3DSwym' in group_names"

    - name: Unmount 3DIndex
      ansible.builtin.mount:
        path: "{{ item }}"
        state: unmounted
      loop:
        - /usr1/NAS
      when: "'3DIndex' in group_names"

    - name: Unmount 3DSwymIndex
      ansible.builtin.mount:
        path: "{{ item }}"
        state: unmounted
      loop:
        - /usr1/NAS
        - /3dswym_data
      when: "'3DSwymIndex' in group_names"

    - name: Unmount FCS
      ansible.builtin.mount:
        path: "{{ item }}"
        state: unmounted
      loop:
        - /usr1/NAS
        - /3dex_data
      when: "'FCS' in group_names"

