---
- hosts: all
  become: true
  tasks:
    - name: Unmount Combined_App_Server trcur001 
      ansible.builtin.mount:
        path: "{{ item }}"
        state: unmounted
      loop:
        - /appshare01
        - /appshare02
        - /3dex_nas
      when: "'Combined_App_Server' in group_names"

    - name: Unmount Combined_App_Server trcur002 
      ansible.builtin.mount:
        path: "{{ item }}"
        state: unmounted
      loop:
        - /appshare01
        - /appshare02
        - /3dex_nas
      when: "'Combined_App_Server' in group_names"

    - name: 3DIndex 
      ansible.builtin.mount:
        path: "{{ item }}"
        state: unmounted
      loop:
        - /3dex_data_NAS
      when: "'3DIndex' in group_names"

    - name: Buider 
      ansible.builtin.mount:
        path: "{{ item }}"
        state: unmounted
      loop:
        - /3dex_data_NAS
      when: "'Builder' in group_names"

    - name: Search 
      ansible.builtin.mount:
        path: "{{ item }}"
        state: unmounted
      loop:
        - /3dex_data_NAS
      when: "'Search' in group_names"

    - name: WBDM 
      ansible.builtin.mount:
        path: "{{ item }}"
        state: unmounted
      loop:
        - /appshare02
      when: "'WBDM' in group_names"